[package]
name = "day_04"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
log = "0.4.6"
env_logger = "0.9.0"
itertools = "0.10.0"
im-rc = "15.0.0"
either = "1.6.1"
ansi_term = "0.12.1"